
name: Terraform CI/CD Workflows

on:
  workflow_dispatch: 
  pull_request:
    branches:
      - development

jobs:
  terraform:
    name: Terraform CI/CD
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3
       
      # Step 2: Set Up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 3: Configure AWS Credentials
      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_DEFAULT_REGION }}

      # Step 4: Initialize Terraform with Backend Configuration
      - name: Terraform Init
        run: |
          terraform init 

      # Step 5: Validate Terraform Configuration
      - name: Terraform Validate
        run: terraform validate

      # Step 6: Check Terraform Formatting
      - name: Terraform Format
        run: terraform fmt -check

      # Step 10: Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Step 11: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
