name: Terraform CI/CD

on:
  push:
    branches:
      - "feature/felix/*"  # Allows triggering on any branch under feature/felix
  pull_request:
  # workflow_dispatch:  # Allows manual trigger

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your AWS region

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0  # Adjust this version if needed

      - name: Navigate to VPC Directory
        run: cd vpc

      - name: Terraform Init
        run: terraform init
        working-directory: ./vpc

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: ./vpc

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./vpc

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./vpc

        # Step 6: SonarQube Code Scan
      - name: SonarQube Scan
        id: sonarqube_scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=sonar1
            -Dsonar.sources=.
            -D-Dsonar.exclusions=**/tfplan
            -X
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Step 7: Quality Gate Check
      - name: Quality Gate Check
        id: quality_gate
        uses: sonarsource/sonarqube-quality-gate-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # - name: Terraform Apply (Main Branch)
      #   # if: github.ref == 'refs/heads/feature/felix/*'
      #   run: terraform apply -auto-approve tfplan
      #   working-directory: ./vpc
